<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    use HasFactory;
    protected $guarded = ['id'];
    //protected $fillable = ['title','excerpt','body','slug'];

    protected $with = ['author','category'];

    public function getRouteKeyName()
    {
        //return parent::getRouteKeyName(); // TODO: Change the autogenerated stub
        return 'slug';
    }



    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function author() //Larave assume that foreign key is author_id, but we have it in DB is user_id
    {
        return $this->belongsTo(User::class,'user_id','id');
    }


}
